version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_healthcare
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: healthcare_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - healthcare_network

volumes:
  postgres_data:
    driver: local

networks:
  healthcare_network:
    driver: bridge
